# data/model paths
dataset_directory: ./data
result_directory: ./results
export_dir: multi_branch

save_dir: ./checkpoints
ast_model: MIT/ast-finetuned-audioset-10-10-0.4593
device: 'cuda'

# 1. General parameters
model: DCASE2025MultiBranch
use_cuda: True
score: MSE
seed: 13711
is_auto_download: False

max_fpr: 0.1
decision_threshold: 0.9

# feature
n_mels: 128
frames: 32
frame_hop_length: 8
n_fft: 1024
hop_length: 512
power: 2.0
fmin: 0.0
fmax: null
win_length: null


# 2. Audio / Feature parameters
n_mels:      64
n_fft:       1024
hop_length:  512
time_steps: 512

# 3. Transformer‐AE hyperparameters
transformer_hidden:   512    # AST hidden size
transformer_nhead:    8      # number of attention heads
transformer_ff:       2048   # feed-forward inner dim
transformer_layers:   6      # encoder layers
transformer_dropout:  0.1    # drop-out in AST config
decoder_layers:       4      # number of decoder layers

# 4. Embedding / diffusion / flow dims
latent_dim:           128
diffusion_unet_dim:   64
diffusion_mults:     [1,2,4]
diffusion_steps:    1000
diffusion_loss_type: 'l2'
flow_dim:            384     # typically 3 * latent_dim
tau: 0.07

# 5. Training hyperparameters
batch_size: 16
epochs:     50
learning_rate: 1e-4
w2:         1.0
w3:         10.0
w4:         1.0
w5:         1.0
w_fusion:    0.1
fusion_var_lambda: 0.1
maml_lr:    1e-2
maml_shots: 5
num_workers: 4
shuffle: True
validation_split: 0.1

# for augmentation
specaug_p: 1.0
specaug_num: 2
specaug_freq: 0.15
specaug_time: 0.15

# for attributes
attr_input_dim: 128
attr_hidden: 64
attr_latent: 10
