# ─ Data & I/O ───────────────────────────────────────────
dataset_directory: ./data
result_directory: ./results
save_dir: ./checkpoints
export_dir: ast_singlebranch
ast_model: MIT/ast-finetuned-audioset-10-10-0.4593
ast_freeze_layers: 10

# ─ General ──────────────────────────────────────────────
model: ASTAutoencoderASD
use_cuda: true
seed: 13711
max_fpr: 0.1

# ─ Feature params (librosa) ─────────────────────────────
sr: 16000
n_mels: 128
n_fft: 1024
hop_length: 512
win_length: 1024
fmin: 50
fmax: 8000
power: 2

# ─ Model hyperparams ───────────────────────────────────
latent_dim: 64        # 16|64|128 → pick after ablation
alpha: 0.5            # fusion weight
latent_noise_std: 0.05

# ─ Training ─────────────────────────────────────────────
batch_size: 16        # adjust to GPU RAM
epochs: 2
learning_rate: 3e-5   # encoder lr; decoder & projection use 1e-4
validation_split: 0.1
num_workers: 4
shuffle: true

# ─ Data augmentation ───────────────────────────────────
specaug_freq_mask: 16
specaug_time_mask: 32
specaug_p: 0.5
time_stretch_range: [0.9, 1.1]
time_stretch_p: 0.3
pitch_shift_range: [-2, 2]
pitch_shift_p: 0.3
noise_std: 0.02
noise_p: 0.5
